
[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["app", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501", "E701", "E702"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
